### ISSUE TITLE
ModuleNotFoundError: No module named 'efficientkan'

### ISSUE THREAD

**Issue by ghostlyFeng** [nasimjamshidi/LAR-IQA#1]
ModuleNotFoundError: No module named 'efficientkan'

**Comment by Raymondmax** [comment]
@ghostlyFeng you can install it using below command:
`pip install git+https://github.com/Blealtan/efficient-kan.git`

**Comment by Raymondmax** [comment]
and replace `from efficientkan.src.efficient_kan import KAN` with `from efficient_kan import KAN`

**Comment by nasimjamshidi** [comment]
@Raymondmax, Thanks for the helpful response. I will fix the bugs and update the repo in the next few days. Stay tuned for the update!

**Comment by ghostlyFeng** [comment]
@Raymondmax Thanks very much. I solved the problem with your method.

**Comment by han030927** [comment]
Hi, Just want to make sure whether the efficient kan can reproduce the result of paper. Or something wrong with my implementation.
I tryed to import efficient kan from above steps, however, it cannot reporduce the same result from the paper. but the pretrained weight using MLP head is exaclty same as the result in the paper， here's the result i runned locally on UHD-IQA:

1. validation set  :

- MLP head :  KRCC 0.6012 PLCC 0.7974 SRCC 0.7914
- KAN head :  KRCC 0.5444 PLCC 0.7463 SRCC 0.7342

2 test  set:

 - MLP head :  KRCC 0.6165 PLCC 0.7739 SRCC 0.8095
- KAN head :  KRCC 0.5574  PLCC 0.7323 SRCC 0.7518

**Comment by nasimjamshidi** [comment]
Hi @han030927,
Thank you very much for sharing your results with me. I’ve added the LAR-IQA KAN results under the "results" subfolder in the repository. Please let me know if there are any discrepancies compared to your measurements.

I'm also re-running the model to cross-check and better understand the differences, as your results show reasonable correlation (indicating they're not random values) but differ from our main model's outcomes.

Thanks again for reporting it to us, and I’ll get back to you after verifying the released code against our internal version.

**Comment by nasimjamshidi** [comment]
Hi again @han030927, 
I checked the code and identified the issue. In the released inference code, we mistakenly applied resizing instead of center cropping for the second transform. 
I've also updated the weights for the KAN model, which should now give you results that match our model exactly. You now have the CSV file with the results, so you can check a few random images to confirm if the numbers align. 
Thank you once again for catching that mistake.

**Comment by han030927** [comment]
Thanks so much for your quick response! I tried with the new weights, I now can get the exactly same results with the paper.
 By the way, replacing 'Centercrop' with 'Resize' indeed has impact on the result. Thanks for the good work!

**Comment by nasimjamshidi** [comment]
You're very welcome! I'm glad to hear the new weights worked for you.
