### ISSUE TITLE
Can't run inference in Colab

### ISSUE THREAD

**Issue by h3clikejava** [nasimjamshidi/LAR-IQA#8]
Can't run inference in Colab: https://colab.research.google.com/drive/1g0hm-S25oYOd5OSFT91uMgZA2UANGSOb?usp=sharing

/content/LAR-IQA/scripts/inference.py:19: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(model_path, map_location=device))
Traceback (most recent call last):
  File "/content/LAR-IQA/scripts/inference.py", line 70, in <module>
    main()
  File "/content/LAR-IQA/scripts/inference.py", line 63, in main
    model = load_model(args.model_path, args.use_kan, device)
  File "/content/LAR-IQA/scripts/inference.py", line 19, in load_model
    model.load_state_dict(torch.load(model_path, map_location=device))
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1384, in load
    return _legacy_load(
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1628, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

![image](https://github.com/user-attachments/assets/fa04217a-e53e-431e-a6f4-87d7199e6063)

**Comment by h3clikejava** [comment]
![image](https://github.com/user-attachments/assets/25aa06b7-7ae7-4ac0-bd9d-8b24cd9fe8f9)

I can't get fullly model... How can i get it?

**Comment by yatoubusha** [comment]
May I ask how it was resolved? Can you provide a manual download link for the pre trained model?

**Comment by nasimjamshidi** [comment]
@yatoubusha: Please refer to the README file for details. The **Inference** section includes a manual Google Colab demo for inference, and the pre-trained models can be downloaded from the **pretrained** sub-folder.
